[22기 안재경] model 생성
wecode-bootcamp-korea/22-2nd-GREAM-backend pull request #1
Opened 2021-07-20 07:33 UTC by anjaekk

## 수정 사항 간략한 한줄 요약
- users, products, orders  models 생성
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항
- 소셜로그인시 카카오 id를 받게되면 user모델에서 email, password등 회원가입 기본사항이 null 값으로 들어가는게 맞을까요..? 
- contract 모델에 foreignkey, unique=True를 했더니 장고에서 one to one필드로 변경하라고 하여 변경했습니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-20 07:50 UTC, anjaekk commented
슬렉 테스트

2021-07-20 07:51 UTC, anjaekk commented
슬렉테스트

2021-07-20 07:53 UTC, anjaekk commented
테스트

2021-07-20 10:12 UTC, lordmyshepherd requested changes

2021-07-20 10:12 UTC, lordmyshepherd commented on orders/models.py
> +    updated_at     = models.DateTimeField(auto_now_add=True)
이런 반복적인 시간기록 요소를 작성한다면, 매번 선언하기 보다는 아래와 같이 추상화된 class를 상속 받아서 구현해주세요.
공통으로 사용되는 경우 core app을 만들어서 models.py에서 관리하는 방향으로 수정해보시면 어떨까요?

```python
class TimeStampModel(models.Model):
    created_at  = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    
    class Meta:
        abstract = True
```

2021-07-20 10:12 UTC, lordmyshepherd commented on orders/models.py
> +    bid_price      = models.DecimalField(max_digits=18, decimal_places=2)
이미 bidding table에 있는 속성이므로 price만으로 의미 전달이 충분한 것 같습니다!

```suggestion
    price      = models.DecimalField(max_digits=18, decimal_places=2)
```

2021-07-20 10:12 UTC, lordmyshepherd commented on orders/models.py
> +    buying_bid  = models.OneToOneField('Bidding', related_name='buying_bid', on_delete=models.SET_NULL, null=True)
Django의 self를 사용해서 만들어주세요~
참고 `models.ManyToManyField('self', through = 'PersonFriends')`

2021-07-20 10:12 UTC, lordmyshepherd commented on orders/models.py
> +    status_name = models.CharField(max_length=45)
변수명은 간단하게 만들어주세요~

```suggestion
class Status(models.Model):
    name = models.CharField(max_length=45)
```

2021-07-20 10:12 UTC, lordmyshepherd commented on products/models.py
> +    original_price        = models.DecimalField(max_digits=18, decimal_places=2)
```suggestion
    english_name          = models.CharField(max_length=100)
    current_buying_price  = models.DecimalField(max_digits=18, decimal_places=2)
    current_selling_price = models.DecimalField(max_digits=18, decimal_places=2)
    author                = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    size                  = models.ForeignKey('Size', on_delete=models.SET_NULL, null=True)
    original_price        = models.DecimalField(max_digits=18, decimal_places=2)
```

2021-07-20 10:12 UTC, lordmyshepherd commented on products/models.py
> +        db_table = 'product_themes'
중간테이블은 `복수-복수` 형태로 만들어주세요~
```suggestion
class ProductTheme(models.Model):
    theme   = models.ForeignKey('Theme', on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)

    class Meta:
        db_table = 'products_themes'
```

2021-07-20 10:12 UTC, lordmyshepherd commented on products/models.py
> +        db_table = 'product_colors'
마찬가지입니다~

2021-07-20 10:12 UTC, lordmyshepherd commented on users/models.py
> +    card_numnber = models.CharField(max_length=45, null=True)
리뷰에서 말씀드린 것 처럼 나중에는 payments table로 분리해서 관리해주세요.

2021-07-20 11:04 UTC, anjaekk commented on orders/models.py
> +    bid_price      = models.DecimalField(max_digits=18, decimal_places=2)
넵! 수정했습니다

2021-07-20 11:04 UTC, anjaekk commented on orders/models.py
> +    status_name = models.CharField(max_length=45)
넵 수정했습니다!

2021-07-20 11:05 UTC, anjaekk commented on products/models.py
> +    original_price        = models.DecimalField(max_digits=18, decimal_places=2)
넵 수정했습니다!

2021-07-20 11:05 UTC, anjaekk commented on products/models.py
> +        db_table = 'product_themes'
넵 수정했습니다!

2021-07-20 11:06 UTC, anjaekk commented on products/models.py
> +        db_table = 'product_colors'
넵! 수정했습니다!

2021-07-20 11:06 UTC, anjaekk commented on users/models.py
> +    card_numnber = models.CharField(max_length=45, null=True)
넵! 알겠습니다! ㅎㅎ

2021-07-20 11:40 UTC, anjaekk commented on orders/models.py
> +    updated_at     = models.DateTimeField(auto_now_add=True)
수정했습니다!

2021-07-21 01:13 UTC, anjaekk commented on orders/models.py
> +    buying_bid  = models.OneToOneField('Bidding', related_name='buying_bid', on_delete=models.SET_NULL, null=True)
병민님! 코멘트 감사합니다!
저희가 다시 살펴보고 이야기해보았는데요,
여기서 selling_bid와 buying_bid의 관계는 ManyToMany가 아닌 OneToOne 관계라고 생각하고,
Bidding 클래스에 참조field를 추가하려면, ForeignKey('self')를 쓰는건 어떨까 생각했습니다!
다만,  두 bid가 서로를 참조하는 것보다 Contract 클래스 자체의 의미가 뚜렷하다고 생각하여, Bidding 클래스에 참조field를 추가하지 않고 Contract 클래스를 유지하는 것은 어떨까 생각해보았습니다!
또한, selling과 buying bid가 같은 테이블에 있는 만큼, 동일 테이블에서 참조관계를 갖는 것이 복잡하지 않을까도 생각했습니다.
혹시 어떤 부분이 잘못되었을지, 병민님의 리뷰를 요청합니다,,,
코멘트로 남겨주시면 정말 감사하겠습니다 병민님,,,,,,,,,,, (바쁘실텐데 꼼꼼히 봐주셔서 감사합니당,,ㅠㅠ)

2021-07-21 01:43 UTC, lordmyshepherd requested changes

2021-07-21 01:43 UTC, lordmyshepherd commented on orders/models.py
> +    buying_bid  = models.OneToOneField('Bidding', related_name='buying_bid', on_delete=models.SET_NULL, null=True)
말씀하신 부분 잘 이해 했습니다!
말씀 들어보니,bidding에서 bidding을 조회할 이유가 없는 것 같네요!

말씀해주신 방법이 좋은 방향인 것 같으니 그대로 진행해주세요~
```
    selling_bid = models.OneToOneField('Bidding', related_name='selling_bid', on_delete=models.SET_NULL, null=True)
    buying_bid  = models.OneToOneField('Bidding', related_name='buying_bid', on_delete=models.SET_NULL, null=True)
```

다만 `unique`에 대한 고려만 추가해주시면 좋을 것 같아요~

2021-07-21 01:59 UTC, anjaekk commented on orders/models.py
> +    buying_bid  = models.OneToOneField('Bidding', related_name='buying_bid', on_delete=models.SET_NULL, null=True)
넵 수정했습니다!

2021-07-21 02:37 UTC, lordmyshepherd approved these changes
LGTM 👍  고생 많으셨습니다!

2021-07-21 02:37 UTC, merged