[22기 김한준] Add: product-list/filter
wecode-bootcamp-korea/22-2nd-GREAM-backend pull request #10
Opened 2021-07-23 06:40 UTC by hanjkim10

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 필터링
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- SHOP 페이지 내 제품 필터링 (작가, 테마, 색상, 크기)
- 상품 가격별 정렬 (즉시 구매가순, 즉시 판매가순, 발매가순(Ascending), 발매가순(Descending)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-26 01:39 UTC, kst6294 reviewed
피드백 확인해주세요 한준님!

2021-07-26 01:39 UTC, kst6294 commented on products/tests.py
> +
id를 지정하는 이유가 있나요?

2021-07-26 01:39 UTC, kst6294 commented on products/tests.py
> +        self.assertEqual(response.status_code, 200)
status_code 만 검증하고 있습니다.

2021-07-26 01:39 UTC, kst6294 commented on products/tests.py
> +    def setUp(self):
setUp 의 경우 각각의 test 가 동작할 때마다 실행됩니다. 즉 테스트마다 그 내용이 변경될 수 있는 객체를 생성할 수 있습니다.
전체에서 공통적으로 사용하고, 그 값이 변경되지 않는 객체들을 생성하는 경우라면 setUpTestData() 메소드를 사용해보시는 것도 좋겠습니다. 해당 메소드는 setUp 처럼 매번 실행하지 않고, 한 번만 생성후에 사용하게 됩니다.

2021-07-26 01:39 UTC, kst6294 commented on products/urls.py
> +    path ('/product', ProductView.as_view()),
/products/product 가 됩니다.
restful 하게 수정해주세요.

2021-07-26 01:39 UTC, kst6294 commented on products/views.py
> +            } for product in products
여기에 해당하는 통신결과 보여주세요.

2021-07-26 02:42 UTC, hanjkim10 commented on products/tests.py
> +        self.assertEqual(response.status_code, 200)
넵 response.json 추가했습니다

2021-07-26 02:42 UTC, hanjkim10 commented on products/tests.py
> +    def setUp(self):
넵 setUpTestData() 메소드로 수정했습니다!

2021-07-26 02:51 UTC, hanjkim10 commented on products/tests.py
> +
작가, 테마, 색상, 사이즈내에서 세부 필터링을 하기 위해서 id를 지정했습니다

예를 들어 작가 카테고리에서 "Bianka Anastazija" 작가의 작품만 필터링 할 때 작가 아이디 1번을 이용해서 필터링 합니다

2021-07-26 02:52 UTC, hanjkim10 commented on products/urls.py
> +    path ('/product', ProductView.as_view()),
넵 수정했습니다

2021-07-26 02:57 UTC, hanjkim10 commented on products/views.py
> +            } for product in products
![스크린샷 2021-07-26 오전 11 56 09](https://user-images.githubusercontent.com/77793868/126926966-b101d0b4-c3eb-425d-b844-e0c49201a264.png)

2021-07-26 06:06 UTC, kst6294 requested changes
확인해주시고, conflict 도 같이 해결해주세요!

2021-07-26 06:06 UTC, kst6294 commented on products/tests.py
> +
그런데 create 할 때 id 는 자동으로 생성되지 않나요?

2021-07-26 06:06 UTC, kst6294 commented on products/views.py
> +        }
공백으로 적절히 구분해주세요.

2021-07-26 06:14 UTC, hanjkim10 commented on products/views.py
> +        }
넵 수정했습니다

2021-07-27 01:33 UTC, kst6294 commented
sort 변동에따른 통신결과도 같이 올려주세요.

2021-07-27 01:37 UTC, hanjkim10 commented
![스크린샷 2021-07-27 오전 10 35 43](https://user-images.githubusercontent.com/77793868/127081024-02e67c29-4294-49b0-89c0-6dead85ab5ac.png)

![스크린샷 2021-07-27 오전 10 35 33](https://user-images.githubusercontent.com/77793868/127081030-9e9f79e5-a5be-4c1c-be8d-c8137b7727c7.png)

![스크린샷 2021-07-27 오전 10 35 19](https://user-images.githubusercontent.com/77793868/127081041-e8025e30-72a3-4745-8fe5-37eff832652b.png)


![스크린샷 2021-07-27 오전 10 35 06](https://user-images.githubusercontent.com/77793868/127081047-9486e90f-f61d-487f-9764-a844902720ad.png)

2021-07-27 05:47 UTC, kst6294 commented
LGTM 👍

2021-07-27 05:47 UTC, merged