[22기 서정민] 입찰 등록 엔드포인트 구현
wecode-bootcamp-korea/22-2nd-GREAM-backend pull request #11
Opened 2021-07-23 11:04 UTC by jungminsayho

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 입찰 등록 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 구매/판매 여부를 query parameter로 전달
- 원하는 가격과 만료기한을 입력하여 입찰 등록
- 구매입찰의 경우, 해당 product의 current_selling_price보다 방금등록한 입찰가격이 더 클때, current_selling_price를 방금등록한 입찰가격으로 업데이트해줌
(즉시판매가(current_selling_price)는 올라와있는 구매입찰 중 가장 높은 가격)
- 판매 입찰의 경우 반대로 적용.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-23 11:09 UTC, jungminsayho commented
#### 테스트통과
![image](https://user-images.githubusercontent.com/83465459/126773428-3d22ff69-5f09-44e5-a230-69a50308d4d3.png)

#### 통신결과
![image](https://user-images.githubusercontent.com/83465459/126773799-b63dcd53-3e07-4e8f-b9c6-593707dd45fd.png)

2021-07-26 02:02 UTC, kst6294 reviewed
피드백 확인해주세요!

2021-07-26 02:02 UTC, kst6294 commented on orders/views.py
> +                expired_within_id = data['expired_within_id'],
마감기한인거죠? 마감기한은 bidding 을 신청하는 사용자가 직접 작성해야하나요?

2021-07-26 02:02 UTC, kst6294 commented on orders/views.py
> +            product = Product.objects.filter(id=product_id)
product id 는 하나만 존재할텐데 filter 를 통해서 쿼리셋을 가져오는 이유가 있나요?

2021-07-26 02:02 UTC, kst6294 commented on orders/views.py
> +                    if bidding.price > product[0].current_selling_price else product[0].current_selling_price
```suggestion
                    if bidding.price > product[0].current_selling_price else product[0].current_selling_price
```

2021-07-26 02:02 UTC, kst6294 commented on orders/views.py
> +                    if bidding.price < product[0].current_buying_price else product[0].current_selling_price
```suggestion
                    if bidding.price < product[0].current_buying_price else product[0].current_selling_price                
```

2021-07-26 02:02 UTC, kst6294 commented on orders/views.py
> +        except KeyError:
전체적으로 key error 만 처리 되어 있네요

2021-07-26 04:26 UTC, jungminsayho commented on orders/views.py
> +                expired_within_id = data['expired_within_id'],
네 맞습니다! 아래 사진처럼 사용자가 입찰 등록시, 직접 선택하게 되어있습니다.

![image](https://user-images.githubusercontent.com/83465459/126932948-0b5f4268-0ea8-4925-8776-232ab0238414.png)

2021-07-26 04:33 UTC, jungminsayho commented on orders/views.py
> +            product = Product.objects.filter(id=product_id)
update() 메소드를 사용하기 위해 filter로 퀴리셋을 가져오는 방법을 사용하였는데,
매번 인덱스를 호출하는 방법보다, get으로 객체를 가져와 업데이트 후 save()를 사용하는 방법으로 수정하였습니다!

2021-07-26 04:35 UTC, jungminsayho commented on orders/views.py
> +        except KeyError:
나머지 에러들을 위에서 if문으로 모두 처리해서, except문으로는 key error만 처리했습니다!

2021-07-26 04:36 UTC, jungminsayho commented on orders/views.py
> +                    if bidding.price > product[0].current_selling_price else product[0].current_selling_price
suggested change 내용이 있을까요!? 두 코드의 차이가 없어 여쭤봅니다!

2021-07-26 04:40 UTC, jungminsayho commented on orders/views.py
> +                    if bidding.price > product[0].current_selling_price else product[0].current_selling_price
근데 삼항연산으로 저렇게 줄을바꿔 쓰는 코드가 올바른지 잘 모르겠습니다,, 저렇게 작성해도 괜찮을까요,, !?

2021-07-26 06:10 UTC, kst6294 requested changes

2021-07-26 06:10 UTC, kst6294 commented on orders/views.py
> +            buy_or_sell = request.GET.get('type', None)
```suggestion
            contract_type = request.GET.get('type', None)
```

2021-07-26 12:20 UTC, jungminsayho commented on orders/views.py
> +            buy_or_sell = request.GET.get('type', None)
확인을 꼼꼼이 했어야했는데, 죄송합니다!
수정했습니다 !!!

2021-07-27 01:31 UTC, kst6294 approved these changes
LGTM 👍

2021-07-27 01:31 UTC, merged