[22기 안재경] 제품 상세페이지 엔드포인트 구현
wecode-bootcamp-korea/22-2nd-GREAM-backend pull request #18
Opened 2021-07-27 14:58 UTC by anjaekk

## 수정 사항 간략한 한줄 요약
- 제품 상세페이지 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
- 들어가는 내용
[메인정보](main_info)
Product - 이름(name), 최근 거래가액(recent_price)즉시판매가격(current_selling_price),  즉시구매가격(current_buying_price), 이미지 3개(image_url)
최근 거래가 비교 가격(comparing_price)
최근 거래가 비율(comparing_price_ratio)

[체결거래](contract_detail)
Filtering - 3개월(3m), 1개월,(1m) 1주일(1w)
Contract - 가격(contract_price), 날짜(contract_date)

[입찰내역](bidding_detail)
판매입찰 - 판매희망가(selling_bidding_price), 날짜(selling_bidding_date)
구매입찰 - 구매희망가(buying_bidding_price), 날짜(buying_bidding_date)

[상품정보](product_info)
작가(author)
모델번호(model_number)
대표색상(color)
발매가(original_price)

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

![image](https://user-images.githubusercontent.com/74139727/127177232-7b84f864-9f75-485c-9ad0-0483c93b0e50.png)

![image](https://user-images.githubusercontent.com/74139727/127177330-2dfd992f-7a65-4e3f-9de5-8fe00ac3249e.png)

2021-07-28 01:05 UTC, kst6294 reviewed
피드백 확인바랍니다!

2021-07-28 01:05 UTC, kst6294 commented on products/tests.py
> +import json,jwt
전체적으로 공백구분 해주세요~

2021-07-28 01:05 UTC, kst6294 commented on products/views.py
> +            return JsonResponse({'message':'VALUE_ERROR'}, status=400)
product_id 로 filter 가 되지 않는 경우, value error 보다는 해당하는 자원이 없는 경우가 더 적절할 것 같습니다.

2021-07-28 01:05 UTC, kst6294 commented on products/views.py
> +            'comparing_price_ratio':comparing_price_ratio
여기에 해당하는 쿼리 로그 캡처해서 올려주시고, 진행된 쿼리 최적화 세션 내용 반영해주세요.

2021-07-28 01:05 UTC, kst6294 commented on products/views.py
> +            status=200)
여기에 해당하는 통신결과도 캡처해서 올려주세요.

2021-07-28 01:28 UTC, anjaekk commented on products/tests.py
> +import json,jwt
네 수정했습니다!

2021-07-28 01:30 UTC, anjaekk commented on products/views.py
> +            return JsonResponse({'message':'VALUE_ERROR'}, status=400)
수정했습니다!

2021-07-28 08:31 UTC, anjaekk commented on products/views.py
> +            'comparing_price_ratio':comparing_price_ratio
![image](https://user-images.githubusercontent.com/74139727/127290789-4d2091ad-1a9c-43aa-a8a6-d4848d3a9952.png)

2021-07-28 08:32 UTC, anjaekk commented on products/views.py
> +            'comparing_price_ratio':comparing_price_ratio
34개에서 21개로 줄이긴 했으나.. 나머지는 어떻게 줄여야할지 모르겠숩니다..

2021-07-28 08:33 UTC, anjaekk commented on products/views.py
> +            status=200)
{
    "message": "SUCCESS",
    "main_info": [
        {
            "name": "Topsy Emerie Quinten Maddison poster",
            "recent_price": "6002000.00",
            "oldest_selling_bidding_id": null,
            "oldest_buying_bidding_id": 1201,
            "current_selling_price": null,
            "current_buyling_price": "5666000.00",
            "image_url": [
                "https://images.unsplash.com/photo-1597873618537-64a04f9e1fb3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMjA3fDB8MXxzZWFyY2h8Mnx8cG9zdGVyfHwwfDJ8fHwxNjI2Njg4OTQ0&ixlib=rb-1.2.1&q=80&w=1080",
                "https://images.unsplash.com/photo-1531626155160-d56b8230eba7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMjA3fDB8MXxzZWFyY2h8ODJ8fHBvc3Rlcnx8MHwyfHx8MTYyNjY4ODk1Mg&ixlib=rb-1.2.1&q=80&w=1080",
                "https://images.unsplash.com/photo-1572635115980-feb7e3247a21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMjA3fDB8MXxzZWFyY2h8MTgyfHxwb3N0ZXJ8fDB8Mnx8fDE2MjY2ODg5NTk&ixlib=rb-1.2.1&q=80&w=1080"
            ],
            "comparing_price": "-3767000.00",
            "comparing_price_ratio": "-38.6"
        }
    ],
    "contract_detail": [
        {
            "contract_date": "2021-07-25",
            "contract_price": "6002000.00"
        },
        {
            "contract_date": "2021-07-25",
            "contract_price": "9769000.00"
        }
    ],
    "contract_all": [
        {
            "contract_date": "2021-06-30",
            "contract_price": "7440000.00"
        },
        {
            "contract_date": "2021-05-25",
            "contract_price": "4663000.00"
        },
        {
            "contract_date": "2021-04-25",
            "contract_price": "7124000.00"
        },
        {
            "contract_date": "2021-07-25",
            "contract_price": "9769000.00"
        },
        {
            "contract_date": "2021-07-25",
            "contract_price": "6002000.00"
        }
    ],
    "bidding_detail": [
        {
            "selling_bidding": [
                {
                    "selling_bidding_date": "2021-07-25",
                    "selling_bidding_price": "9769000.00"
                },
                {
                    "selling_bidding_date": "2021-07-25",
                    "selling_bidding_price": "8907000.00"
                },
                {
                    "selling_bidding_date": "2021-05-25",
                    "selling_bidding_price": "7440000.00"
                },
                {
                    "selling_bidding_date": "2021-07-25",
                    "selling_bidding_price": "7124000.00"
                },
                {
                    "selling_bidding_date": "2021-07-25",
                    "selling_bidding_price": "6002000.00"
                },
                {
                    "selling_bidding_date": "2021-07-25",
                    "selling_bidding_price": "5666000.00"
                },
                {
                    "selling_bidding_date": "2021-07-25",
                    "selling_bidding_price": "4663000.00"
                }
            ],
            "buying_bidding": [
                {
                    "buying_bidding_date": "2021-05-25",
                    "buying_bidding_price": "4663000.00"
                },
                {
                    "buying_bidding_date": "2021-07-25",
                    "buying_bidding_price": "5666000.00"
                },
                {
                    "buying_bidding_date": "2021-07-25",
                    "buying_bidding_price": "6002000.00"
                },
                {
                    "buying_bidding_date": "2021-07-25",
                    "buying_bidding_price": "7124000.00"
                },
                {
                    "buying_bidding_date": "2021-02-02",
                    "buying_bidding_price": "7440000.00"
                },
                {
                    "buying_bidding_date": "2021-07-25",
                    "buying_bidding_price": "8907000.00"
                },
                {
                    "buying_bidding_date": "2021-07-25",
                    "buying_bidding_price": "9769000.00"
                }
            ]
        }
    ],
    "product_info": [
        {
            "model_number": 1,
            "author": "Bianka Anastazija",
            "color": [
                "Red"
            ],
            "original_price": "654000.00"
        }
    ]
}

2021-07-28 10:11 UTC, kst6294 requested changes, later dismissed
확인바랍니다!

2021-07-28 10:11 UTC, kst6294 commented on products/views.py
> +class ProductDetailView(View):
재경님! 
현재 전달하고자 하는 데이터들이 하나의 View 안에 포함되어 있다보니,
코드가 아직 정리되지 않은 것 같습니다. 
전달하고자 하는 섹션별로 구분해주시고, 해당하는 기능에 대한 설명을 주석으로 남겨주세요!
그리고 내일 오전에 같이 한 번 보시죠!

2021-07-29 06:49 UTC, kst6294 commented
conflict 해결해주세요!

2021-07-29 07:32 UTC, kst6294 commented
conflict 다시 해결해주세요!

2021-07-29 09:42 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-07-29 10:00 UTC, lordmyshepherd approved these changes

2021-07-29 11:35 UTC, lordmyshepherd approved these changes
LGTM 👍  고생 많으셨습니다!!

2021-07-29 12:18 UTC, merged