[22기 서정민] 구매/판매/입찰페이지 정보 제공
wecode-bootcamp-korea/22-2nd-GREAM-backend pull request #8
Opened 2021-07-22 16:28 UTC by jungminsayho

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 구매/판매/입찰페이지 정보 제공 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 즉시구매, 즉시판매, 입찰등록 페이지 모두 같은 정보를 필요로 하여, 하나의 api로 구현
- 즉시구매가/즉시판매가: 입찰이 등록될때마다 product 모델에서 업데이트 된 값을 불러옴
- selling_bid/buying_bid는 즉시구매 버튼을 누를 시 해당 bid 데이터를 넘겨주기 위함

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-22 16:31 UTC, jungminsayho commented
![image](https://user-images.githubusercontent.com/83465459/126675035-81cbb28e-ce9d-4fe3-8b67-b583e0f2371c.png)

2021-07-23 01:49 UTC, kst6294 requested changes
피드백 확인부탁드립니다!

2021-07-23 01:49 UTC, kst6294 commented on orders/tests.py
> +        Product.objects.filter(id=2).update(current_selling_price=110000)
setUp 의 경우 각각의 test 가 동작할 때마다 실행됩니다. 즉 테스트마다 그 내용이 변경될 수 있는 객체를 생성할 수 있습니다.
전체에서 공통적으로 사용하고, 그 값이 변경되지 않는 객체들을 생성하는 경우라면 setUpTestData() 메소드를 사용해보시는 것도 좋겠습니다. 해당 메소드는 setUp 처럼 매번 실행하지 않고, 한 번만 생성후에 사용하게 됩니다.

2021-07-23 01:49 UTC, kst6294 commented on orders/tests.py
> +        access_token = jwt.encode({"user_id" : 1}, SECRET_KEY, ALGORITHMS)
token 을 매번 테스트 안에서 생성하는 것보다는 setup 을 할 때 미리 token 을 생성해서 사용해주세요!

2021-07-23 01:49 UTC, kst6294 commented on orders/tests.py
> +        access_token = jwt.encode({"user_id" : 1}, SECRET_KEY, algorithm="HS256")
가능한 알고리즘은 외부에서 import 로 사용해주세요!

2021-07-23 01:49 UTC, kst6294 commented on orders/urls.py
> +    path('/<int:product_id>', BiddingPageView.as_view()),
이 엔드포인트에 대해 설명한번 해주시겠어요?

2021-07-23 01:49 UTC, kst6294 commented on orders/views.py
> +    def get(self, request, product_id):
이 뷰에 해당하는 로직에 대해서 설명부탁드립니다.

2021-07-23 01:49 UTC, kst6294 commented
통신결과도 같이 올려주세요~!

2021-07-23 04:38 UTC, jungminsayho commented on orders/tests.py
> +        Product.objects.filter(id=2).update(current_selling_price=110000)
넵, 알려주신 메소드로 수정했습니다! 감사합니당,,

2021-07-23 04:45 UTC, jungminsayho commented on orders/tests.py
> +        access_token = jwt.encode({"user_id" : 1}, SECRET_KEY, ALGORITHMS)
넵 수정했습니다!

2021-07-23 04:45 UTC, jungminsayho commented on orders/tests.py
> +        access_token = jwt.encode({"user_id" : 1}, SECRET_KEY, algorithm="HS256")
넵 수정했습니다!

2021-07-23 04:49 UTC, jungminsayho commented on orders/urls.py
> +    path('/<int:product_id>', BiddingPageView.as_view()),
해당제품에 대한 즉시구매/즉시판매/입찰 페이지에 정보들을 제공하는 엔드포인트로,
상품 id로 끝내는 것보다, 입찰페이지에 대한 정보를 제공한다는 의미를 전달하기 위해 "/<int:product_id>/bidding-page"로 수정했습니다!

2021-07-23 05:05 UTC, jungminsayho commented on orders/views.py
> +    def get(self, request, product_id):
즉시구매가는 판매입찰이 올라온 가격 중 가장 낮은가격으로, 입찰이 등록될 때마다 product 모델 내의 current_buying_price 값이 업데이트 됩니다.
즉시판매가는 구매입찰이 올라온 가격 중 가장 높은가격으로, 입찰이 등록될 때마다 product 모델 내의 current_selling_price 값이 업데이트 됩니다.

즉시구매가/즉시판매가는 product객체에서 받아옵니다.

selling_bid는 유저가 구매를 하고자 할 때, 즉시구매가 가능한 판매입찰건을 변수로 지정해주고, 구매체결 시 매칭된 입찰건의 id를 json으로 넘겨주기 위함입니다.
이 내용을 페이지get api에서 제외하고 입찰post api에만 포함시키지 않은 이유는, 페이지를 보고있던 중에 유저가 보고있는 판매입찰건이 체결될 도 있기 때문에, 그 경우에는 post에서 해당 입찰건을 찾을 수 없다는 오류를 걸러주기 위함입니다.

페이지에 제공하는 정보로는, product에 대한 정보, 결제정보를 포함한 user의 정보가 있습니다.

2021-07-25 07:42 UTC, closed without merging