[22기 서정민] 즉시구매/즉시판매 체결 엔드포인트 구현
wecode-bootcamp-korea/22-2nd-GREAM-backend pull request #9
Opened 2021-07-22 17:17 UTC by jungminsayho

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 구매/판매 체결 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 구매/판매 여부를 query parameter로 받아 구분
- 이전페이지에서 넘어올 때, selling_bid_id와 buying_bid_id를 json으로 전달받음
- 즉시구매/즉시판매를 할 경우, 해당 제품에 대한 본인의 입찰 건이 등록되어 있지 않은 상태이므로, 
Bidding에 입찰 건을 생성 한 후, 바로 구매/판매로 연결 > contract 체결
- contract 체결 후, 각각의 입찰건들의 상태를 '체결완료'(id=3)로 변경

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-22 17:18 UTC, jungminsayho commented
![image](https://user-images.githubusercontent.com/83465459/126681220-2bf234c2-fa22-4a15-b248-9ea482d60088.png)

2021-07-23 01:51 UTC, kst6294 requested changes
이 뷰도 설명듣고 피드백 하겠습니다!

2021-07-23 01:51 UTC, kst6294 commented on orders/tests.py
> +    def setUp(self):
다른 pr 의 피드백 확인해주세요!

2021-07-23 01:51 UTC, kst6294 commented on orders/tests.py
> +        access_token = jwt.encode({"user_id" : 2}, SECRET_KEY, ALGORITHMS)
피드백 동일합니다!

2021-07-23 01:51 UTC, kst6294 commented on orders/urls.py
> +    path('/<int:product_id>/contract', ContractView.as_view()),
url 이 어떻게 구성되는지 여기도 설명부탁드립니다.

2021-07-23 05:42 UTC, jungminsayho commented on orders/tests.py
> +    def setUp(self):
넵 수정했습니다!

2021-07-23 05:42 UTC, jungminsayho commented on orders/tests.py
> +        access_token = jwt.encode({"user_id" : 2}, SECRET_KEY, ALGORITHMS)
넵넵 수정했습니다!

2021-07-23 05:45 UTC, jungminsayho commented on orders/urls.py
> +    path('/<int:product_id>/contract', ContractView.as_view()),
"/orders/<int:product_id>/contract
해당상품에 대한 즉시구매/즉시판매를 위한 엔드포인트이고, 해당상품의 id를 path parameter로 받는 방법으로 작성했습니다.
즉시구매/즉시판매의 경우 'contract'로, 입찰등록의 경우 'bidding'으로 엔드포인트를 나눴습니다. (bidding은 다른 브랜치로 올리겠습니다!)

2021-07-26 01:54 UTC, kst6294 reviewed
피드백 확인바랍니다!

2021-07-26 01:54 UTC, kst6294 commented on orders/views.py
> +            buy_or_sell = request.GET.get('type', None)
```suggestion
            contract_type = request.GET.get('type', None)
```

2021-07-26 01:54 UTC, kst6294 commented on orders/views.py
> +class ContractView(View):
여기에 해당하는 통신결과도 같이 올려주세요!

2021-07-26 01:54 UTC, kst6294 commented on orders/views.py
> +        except KeyError:
key error 외에는 에러가 발생하지 않나요?

2021-07-26 01:54 UTC, kst6294 commented on orders/views.py
> +            return JsonResponse({'message': 'CONTRACT_SUCCESS'}, status=201)
중간중간에 해당 로직이 어떠한 기능을 수행하는지 주석으로 설명한번 남겨주시겠어요?

2021-07-26 02:50 UTC, jungminsayho commented on orders/views.py
> +class ContractView(View):
구매의 경우, buying_bid는 로직상에서 새로 create한 객체를 받아 사용할 거기 때문에,
post body안에는 buying_bid_id가 빈값으로 들어옵니다.

![image](https://user-images.githubusercontent.com/83465459/126926505-882ef013-639f-4a10-a1cf-0ff529ed85fb.png)

2021-07-26 02:51 UTC, jungminsayho commented on orders/views.py
> +        except KeyError:
나머지 발생할 수 있는 에러들은 위에서 if문으로 모두 처리하여, except문으로는 keyerror만 처리했습니다.

2021-07-26 02:51 UTC, jungminsayho commented on orders/views.py
> +            return JsonResponse({'message': 'CONTRACT_SUCCESS'}, status=201)
넵 남겨서 다시 올리겠습니다 !

2021-07-26 02:51 UTC, jungminsayho commented on orders/views.py
> +            buy_or_sell = request.GET.get('type', None)
수정했습니다 !

2021-07-26 04:14 UTC, merged